sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer self-update && composer --version
  - composer install

services:
    - redis-server

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache